#############################################################################
# Makefile for building: Ver4
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Ver4.pro
# Template: app
# Command: /opt/Qt5.8/bin/qmake -o Makefile Ver4.pro -config release
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.8/include -I/opt/Qt5.8/include/QtWidgets -I/opt/Qt5.8/include/QtGui -I/opt/Qt5.8/include/QtNetwork -I/opt/Qt5.8/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/opt/Qt5.8/mkspecs/linux-g++
QMAKE         = /opt/Qt5.8/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Ver41.0.0
DISTDIR = /home/Vyacheslav/Projects/Ver4/.tmp/Ver41.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/Qt5.8/lib -lQt5Widgets -L/opt/Qt5.8/plugins/platforms -lqxcb -L/opt/Qt5.8/plugins/xcbglintegrations -lqxcb-egl-integration -lqxcb-glx-integration -lQt5XcbQpa -lQt5LinuxAccessibilitySupport -lQt5AccessibilitySupport -lQt5GlxSupport -lXrender -lxcb-static -lxcb-glx -lSM -lICE -L/opt/Qt5.8/plugins/imageformats -lqgif -lqicns -lqico -lqjpeg -lqtga -lqtiff -lqwbmp -lqwebp -L/opt/Qt5.8/plugins/egldeviceintegrations -lqeglfs-kms-egldevice-integration -lQt5EglFsKmsSupport -ldrm -lqeglfs-x11-integration -lQt5EglFSDeviceIntegration -lQt5EventDispatcherSupport -lQt5ServiceSupport -lQt5ThemeSupport -lQt5FontDatabaseSupport -lQt5FbSupport -lQt5EglSupport -lXext -lQt5PlatformCompositorSupport -lQt5InputSupport -lQt5Gui -lpng16 -lqtharfbuzz -lQt5DeviceDiscoverySupport -lxcb -lX11 -lX11-xcb -lfontconfig -lfreetype -lEGL -L/opt/Qt5.8/plugins/bearer -lqconnmanbearer -lqgenericbearer -lqnmbearer -lQt5Network -lQt5DBus -lQt5Core -lm -ldl -lrt -lz -lpcre16 -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		connector.cpp \
		errorwindow.cpp \
		encoder.cpp /home/Vyacheslav/Projects/Ver4/ver4_plugin_import.cpp \
		moc_mainwindow.cpp \
		moc_connector.cpp \
		moc_errorwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		connector.o \
		errorwindow.o \
		encoder.o \
		ver4_plugin_import.o \
		moc_mainwindow.o \
		moc_connector.o \
		moc_errorwindow.o
DIST          = /opt/Qt5.8/mkspecs/features/spec_pre.prf \
		/opt/Qt5.8/mkspecs/common/unix.conf \
		/opt/Qt5.8/mkspecs/common/linux.conf \
		/opt/Qt5.8/mkspecs/common/sanitize.conf \
		/opt/Qt5.8/mkspecs/common/gcc-base.conf \
		/opt/Qt5.8/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.8/mkspecs/common/g++-base.conf \
		/opt/Qt5.8/mkspecs/common/g++-unix.conf \
		/opt/Qt5.8/mkspecs/qconfig.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_assimpsceneio.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-kms-egldevice-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-x11-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qico.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimalegl.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsqlite.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qvnc.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-egl-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-glx-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb.pri \
		/opt/Qt5.8/mkspecs/features/qt_functions.prf \
		/opt/Qt5.8/mkspecs/features/qt_config.prf \
		/opt/Qt5.8/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.8/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.8/mkspecs/features/toolchain.prf \
		/opt/Qt5.8/mkspecs/features/default_pre.prf \
		/opt/Qt5.8/mkspecs/features/resolve_config.prf \
		/opt/Qt5.8/mkspecs/features/default_post.prf \
		/opt/Qt5.8/mkspecs/features/warn_on.prf \
		/opt/Qt5.8/mkspecs/features/qt.prf \
		/opt/Qt5.8/mkspecs/features/resources.prf \
		/opt/Qt5.8/mkspecs/features/moc.prf \
		/opt/Qt5.8/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.8/mkspecs/features/uic.prf \
		/opt/Qt5.8/mkspecs/features/unix/thread.prf \
		/opt/Qt5.8/mkspecs/features/qmake_use.prf \
		/opt/Qt5.8/mkspecs/features/file_copies.prf \
		/opt/Qt5.8/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.8/mkspecs/features/exceptions.prf \
		/opt/Qt5.8/mkspecs/features/yacc.prf \
		/opt/Qt5.8/mkspecs/features/lex.prf \
		Ver4.pro mainwindow.h \
		connector.h \
		errorwindow.h \
		const.h \
		encoder.h main.cpp \
		mainwindow.cpp \
		connector.cpp \
		errorwindow.cpp \
		encoder.cpp
QMAKE_TARGET  = Ver4
DESTDIR       = 
TARGET        = Ver4


first: all
####### Build rules

$(TARGET): /opt/Qt5.8/lib/libQt5Widgets.a /opt/Qt5.8/lib/libQt5Gui.a /opt/Qt5.8/lib/libQt5Network.a /opt/Qt5.8/lib/libQt5Core.a ui_mainwindow.h ui_errorwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ver4.pro /opt/Qt5.8/mkspecs/linux-g++/qmake.conf /opt/Qt5.8/mkspecs/features/spec_pre.prf \
		/opt/Qt5.8/mkspecs/common/unix.conf \
		/opt/Qt5.8/mkspecs/common/linux.conf \
		/opt/Qt5.8/mkspecs/common/sanitize.conf \
		/opt/Qt5.8/mkspecs/common/gcc-base.conf \
		/opt/Qt5.8/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.8/mkspecs/common/g++-base.conf \
		/opt/Qt5.8/mkspecs/common/g++-unix.conf \
		/opt/Qt5.8/mkspecs/qconfig.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_assimpsceneio.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-kms-egldevice-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-x11-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qico.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimalegl.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsqlite.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qvnc.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-egl-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-glx-integration.pri \
		/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb.pri \
		/opt/Qt5.8/mkspecs/features/qt_functions.prf \
		/opt/Qt5.8/mkspecs/features/qt_config.prf \
		/opt/Qt5.8/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.8/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.8/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.8/mkspecs/features/toolchain.prf \
		/opt/Qt5.8/mkspecs/features/default_pre.prf \
		/opt/Qt5.8/mkspecs/features/resolve_config.prf \
		/opt/Qt5.8/mkspecs/features/default_post.prf \
		/opt/Qt5.8/mkspecs/features/warn_on.prf \
		/opt/Qt5.8/mkspecs/features/qt.prf \
		/opt/Qt5.8/mkspecs/features/resources.prf \
		/opt/Qt5.8/mkspecs/features/moc.prf \
		/opt/Qt5.8/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.8/mkspecs/features/uic.prf \
		/opt/Qt5.8/mkspecs/features/unix/thread.prf \
		/opt/Qt5.8/mkspecs/features/qmake_use.prf \
		/opt/Qt5.8/mkspecs/features/file_copies.prf \
		/opt/Qt5.8/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.8/mkspecs/features/exceptions.prf \
		/opt/Qt5.8/mkspecs/features/yacc.prf \
		/opt/Qt5.8/mkspecs/features/lex.prf \
		Ver4.pro \
		/opt/Qt5.8/lib/libQt5Widgets.prl \
		/opt/Qt5.8/lib/libQt5Gui.prl \
		/opt/Qt5.8/lib/libQt5Network.prl \
		/opt/Qt5.8/lib/libQt5Core.prl \
		/opt/Qt5.8/plugins/platforms/libqxcb.prl \
		/opt/Qt5.8/plugins/xcbglintegrations/libqxcb-egl-integration.prl \
		/opt/Qt5.8/plugins/xcbglintegrations/libqxcb-glx-integration.prl \
		/opt/Qt5.8/plugins/imageformats/libqgif.prl \
		/opt/Qt5.8/plugins/imageformats/libqicns.prl \
		/opt/Qt5.8/plugins/imageformats/libqico.prl \
		/opt/Qt5.8/plugins/imageformats/libqjpeg.prl \
		/opt/Qt5.8/plugins/imageformats/libqtga.prl \
		/opt/Qt5.8/plugins/imageformats/libqtiff.prl \
		/opt/Qt5.8/plugins/imageformats/libqwbmp.prl \
		/opt/Qt5.8/plugins/imageformats/libqwebp.prl \
		/opt/Qt5.8/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.prl \
		/opt/Qt5.8/plugins/egldeviceintegrations/libqeglfs-x11-integration.prl \
		/opt/Qt5.8/plugins/bearer/libqconnmanbearer.prl \
		/opt/Qt5.8/plugins/bearer/libqgenericbearer.prl \
		/opt/Qt5.8/plugins/bearer/libqnmbearer.prl
	$(QMAKE) -o Makefile Ver4.pro -config release
/opt/Qt5.8/mkspecs/features/spec_pre.prf:
/opt/Qt5.8/mkspecs/common/unix.conf:
/opt/Qt5.8/mkspecs/common/linux.conf:
/opt/Qt5.8/mkspecs/common/sanitize.conf:
/opt/Qt5.8/mkspecs/common/gcc-base.conf:
/opt/Qt5.8/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.8/mkspecs/common/g++-base.conf:
/opt/Qt5.8/mkspecs/common/g++-unix.conf:
/opt/Qt5.8/mkspecs/qconfig.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.8/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_assimpsceneio.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_evdevgamepad.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_gltfsceneio.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-kms-egldevice-integration.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs-x11-integration.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qeglfs.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qgif.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qicns.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qico.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qjpeg.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qlinuxfb.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimal.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qminimalegl.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qnmbearer.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qoffscreen.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qsqlite.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvg.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qsvgicon.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtga.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtiff.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtsocketcanbus.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qttinycanbus.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qvnc.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qwbmp.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qwebp.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-egl-integration.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb-glx-integration.pri:
/opt/Qt5.8/mkspecs/modules/qt_plugin_qxcb.pri:
/opt/Qt5.8/mkspecs/features/qt_functions.prf:
/opt/Qt5.8/mkspecs/features/qt_config.prf:
/opt/Qt5.8/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.8/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt5.8/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.8/mkspecs/features/toolchain.prf:
/opt/Qt5.8/mkspecs/features/default_pre.prf:
/opt/Qt5.8/mkspecs/features/resolve_config.prf:
/opt/Qt5.8/mkspecs/features/default_post.prf:
/opt/Qt5.8/mkspecs/features/warn_on.prf:
/opt/Qt5.8/mkspecs/features/qt.prf:
/opt/Qt5.8/mkspecs/features/resources.prf:
/opt/Qt5.8/mkspecs/features/moc.prf:
/opt/Qt5.8/mkspecs/features/unix/opengl.prf:
/opt/Qt5.8/mkspecs/features/uic.prf:
/opt/Qt5.8/mkspecs/features/unix/thread.prf:
/opt/Qt5.8/mkspecs/features/qmake_use.prf:
/opt/Qt5.8/mkspecs/features/file_copies.prf:
/opt/Qt5.8/mkspecs/features/testcase_targets.prf:
/opt/Qt5.8/mkspecs/features/exceptions.prf:
/opt/Qt5.8/mkspecs/features/yacc.prf:
/opt/Qt5.8/mkspecs/features/lex.prf:
Ver4.pro:
/opt/Qt5.8/lib/libQt5Widgets.prl:
/opt/Qt5.8/lib/libQt5Gui.prl:
/opt/Qt5.8/lib/libQt5Network.prl:
/opt/Qt5.8/lib/libQt5Core.prl:
/opt/Qt5.8/plugins/platforms/libqxcb.prl:
/opt/Qt5.8/plugins/xcbglintegrations/libqxcb-egl-integration.prl:
/opt/Qt5.8/plugins/xcbglintegrations/libqxcb-glx-integration.prl:
/opt/Qt5.8/plugins/imageformats/libqgif.prl:
/opt/Qt5.8/plugins/imageformats/libqicns.prl:
/opt/Qt5.8/plugins/imageformats/libqico.prl:
/opt/Qt5.8/plugins/imageformats/libqjpeg.prl:
/opt/Qt5.8/plugins/imageformats/libqtga.prl:
/opt/Qt5.8/plugins/imageformats/libqtiff.prl:
/opt/Qt5.8/plugins/imageformats/libqwbmp.prl:
/opt/Qt5.8/plugins/imageformats/libqwebp.prl:
/opt/Qt5.8/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.prl:
/opt/Qt5.8/plugins/egldeviceintegrations/libqeglfs-x11-integration.prl:
/opt/Qt5.8/plugins/bearer/libqconnmanbearer.prl:
/opt/Qt5.8/plugins/bearer/libqgenericbearer.prl:
/opt/Qt5.8/plugins/bearer/libqnmbearer.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Ver4.pro -config release

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt5.8/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h connector.h errorwindow.h const.h encoder.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp connector.cpp errorwindow.cpp encoder.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui errorwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/Vyacheslav/Projects/Ver4/ver4_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt5.8/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/Qt5.8/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_connector.cpp moc_errorwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_connector.cpp moc_errorwindow.cpp
moc_mainwindow.cpp: /opt/Qt5.8/include/QtWidgets/QMainWindow \
		/opt/Qt5.8/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.8/include/QtGui/qtguiglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtGui/qtgui-config.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.8/include/QtWidgets/qwidget.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qmargins.h \
		/opt/Qt5.8/include/QtGui/qpaintdevice.h \
		/opt/Qt5.8/include/QtCore/qrect.h \
		/opt/Qt5.8/include/QtCore/qsize.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtGui/qpalette.h \
		/opt/Qt5.8/include/QtGui/qcolor.h \
		/opt/Qt5.8/include/QtGui/qrgb.h \
		/opt/Qt5.8/include/QtGui/qrgba64.h \
		/opt/Qt5.8/include/QtGui/qbrush.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtGui/qmatrix.h \
		/opt/Qt5.8/include/QtGui/qpolygon.h \
		/opt/Qt5.8/include/QtGui/qregion.h \
		/opt/Qt5.8/include/QtCore/qdatastream.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qline.h \
		/opt/Qt5.8/include/QtGui/qtransform.h \
		/opt/Qt5.8/include/QtGui/qpainterpath.h \
		/opt/Qt5.8/include/QtGui/qimage.h \
		/opt/Qt5.8/include/QtGui/qpixelformat.h \
		/opt/Qt5.8/include/QtGui/qpixmap.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtGui/qfont.h \
		/opt/Qt5.8/include/QtGui/qfontmetrics.h \
		/opt/Qt5.8/include/QtGui/qfontinfo.h \
		/opt/Qt5.8/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.8/include/QtGui/qcursor.h \
		/opt/Qt5.8/include/QtGui/qkeysequence.h \
		/opt/Qt5.8/include/QtGui/qevent.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qurl.h \
		/opt/Qt5.8/include/QtCore/qurlquery.h \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h \
		/opt/Qt5.8/include/QtGui/qvector2d.h \
		/opt/Qt5.8/include/QtGui/qtouchdevice.h \
		/opt/Qt5.8/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.8/include/QtGui/qicon.h \
		errorwindow.h \
		/opt/Qt5.8/include/QtWidgets/QDialog \
		/opt/Qt5.8/include/QtWidgets/qdialog.h \
		/opt/Qt5.8/include/QtNetwork/QAbstractSocket \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		connector.h \
		/opt/Qt5.8/include/QtNetwork/QTcpSocket \
		/opt/Qt5.8/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/QObject \
		const.h \
		encoder.h \
		mainwindow.h \
		moc_predefs.h \
		/opt/Qt5.8/bin/moc
	/opt/Qt5.8/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt5.8/mkspecs/linux-g++ -I/home/Vyacheslav/Projects/Ver4 -I/opt/Qt5.8/include -I/opt/Qt5.8/include/QtWidgets -I/opt/Qt5.8/include/QtGui -I/opt/Qt5.8/include/QtNetwork -I/opt/Qt5.8/include/QtCore -I/usr/include/c++/5.3.1 -I/usr/include/c++/5.3.1/x86_64-redhat-linux -I/usr/include/c++/5.3.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_connector.cpp: /opt/Qt5.8/include/QtNetwork/QTcpSocket \
		/opt/Qt5.8/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/QObject \
		const.h \
		encoder.h \
		connector.h \
		moc_predefs.h \
		/opt/Qt5.8/bin/moc
	/opt/Qt5.8/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt5.8/mkspecs/linux-g++ -I/home/Vyacheslav/Projects/Ver4 -I/opt/Qt5.8/include -I/opt/Qt5.8/include/QtWidgets -I/opt/Qt5.8/include/QtGui -I/opt/Qt5.8/include/QtNetwork -I/opt/Qt5.8/include/QtCore -I/usr/include/c++/5.3.1 -I/usr/include/c++/5.3.1/x86_64-redhat-linux -I/usr/include/c++/5.3.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include -I/usr/local/include -I/usr/include connector.h -o moc_connector.cpp

moc_errorwindow.cpp: /opt/Qt5.8/include/QtWidgets/QDialog \
		/opt/Qt5.8/include/QtWidgets/qdialog.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.8/include/QtGui/qtguiglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtGui/qtgui-config.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.8/include/QtWidgets/qwidget.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qmargins.h \
		/opt/Qt5.8/include/QtGui/qpaintdevice.h \
		/opt/Qt5.8/include/QtCore/qrect.h \
		/opt/Qt5.8/include/QtCore/qsize.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtGui/qpalette.h \
		/opt/Qt5.8/include/QtGui/qcolor.h \
		/opt/Qt5.8/include/QtGui/qrgb.h \
		/opt/Qt5.8/include/QtGui/qrgba64.h \
		/opt/Qt5.8/include/QtGui/qbrush.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtGui/qmatrix.h \
		/opt/Qt5.8/include/QtGui/qpolygon.h \
		/opt/Qt5.8/include/QtGui/qregion.h \
		/opt/Qt5.8/include/QtCore/qdatastream.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qline.h \
		/opt/Qt5.8/include/QtGui/qtransform.h \
		/opt/Qt5.8/include/QtGui/qpainterpath.h \
		/opt/Qt5.8/include/QtGui/qimage.h \
		/opt/Qt5.8/include/QtGui/qpixelformat.h \
		/opt/Qt5.8/include/QtGui/qpixmap.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtGui/qfont.h \
		/opt/Qt5.8/include/QtGui/qfontmetrics.h \
		/opt/Qt5.8/include/QtGui/qfontinfo.h \
		/opt/Qt5.8/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.8/include/QtGui/qcursor.h \
		/opt/Qt5.8/include/QtGui/qkeysequence.h \
		/opt/Qt5.8/include/QtGui/qevent.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qurl.h \
		/opt/Qt5.8/include/QtCore/qurlquery.h \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h \
		/opt/Qt5.8/include/QtGui/qvector2d.h \
		/opt/Qt5.8/include/QtGui/qtouchdevice.h \
		/opt/Qt5.8/include/QtNetwork/QAbstractSocket \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		errorwindow.h \
		moc_predefs.h \
		/opt/Qt5.8/bin/moc
	/opt/Qt5.8/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/Qt5.8/mkspecs/linux-g++ -I/home/Vyacheslav/Projects/Ver4 -I/opt/Qt5.8/include -I/opt/Qt5.8/include/QtWidgets -I/opt/Qt5.8/include/QtGui -I/opt/Qt5.8/include/QtNetwork -I/opt/Qt5.8/include/QtCore -I/usr/include/c++/5.3.1 -I/usr/include/c++/5.3.1/x86_64-redhat-linux -I/usr/include/c++/5.3.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include -I/usr/local/include -I/usr/include errorwindow.h -o moc_errorwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_errorwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_errorwindow.h
ui_mainwindow.h: mainwindow.ui \
		/opt/Qt5.8/bin/uic
	/opt/Qt5.8/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_errorwindow.h: errorwindow.ui \
		/opt/Qt5.8/bin/uic
	/opt/Qt5.8/bin/uic errorwindow.ui -o ui_errorwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt5.8/include/QtWidgets/QMainWindow \
		/opt/Qt5.8/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.8/include/QtGui/qtguiglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtGui/qtgui-config.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.8/include/QtWidgets/qwidget.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qmargins.h \
		/opt/Qt5.8/include/QtGui/qpaintdevice.h \
		/opt/Qt5.8/include/QtCore/qrect.h \
		/opt/Qt5.8/include/QtCore/qsize.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtGui/qpalette.h \
		/opt/Qt5.8/include/QtGui/qcolor.h \
		/opt/Qt5.8/include/QtGui/qrgb.h \
		/opt/Qt5.8/include/QtGui/qrgba64.h \
		/opt/Qt5.8/include/QtGui/qbrush.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtGui/qmatrix.h \
		/opt/Qt5.8/include/QtGui/qpolygon.h \
		/opt/Qt5.8/include/QtGui/qregion.h \
		/opt/Qt5.8/include/QtCore/qdatastream.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qline.h \
		/opt/Qt5.8/include/QtGui/qtransform.h \
		/opt/Qt5.8/include/QtGui/qpainterpath.h \
		/opt/Qt5.8/include/QtGui/qimage.h \
		/opt/Qt5.8/include/QtGui/qpixelformat.h \
		/opt/Qt5.8/include/QtGui/qpixmap.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtGui/qfont.h \
		/opt/Qt5.8/include/QtGui/qfontmetrics.h \
		/opt/Qt5.8/include/QtGui/qfontinfo.h \
		/opt/Qt5.8/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.8/include/QtGui/qcursor.h \
		/opt/Qt5.8/include/QtGui/qkeysequence.h \
		/opt/Qt5.8/include/QtGui/qevent.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qurl.h \
		/opt/Qt5.8/include/QtCore/qurlquery.h \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h \
		/opt/Qt5.8/include/QtGui/qvector2d.h \
		/opt/Qt5.8/include/QtGui/qtouchdevice.h \
		/opt/Qt5.8/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.8/include/QtGui/qicon.h \
		errorwindow.h \
		/opt/Qt5.8/include/QtWidgets/QDialog \
		/opt/Qt5.8/include/QtWidgets/qdialog.h \
		/opt/Qt5.8/include/QtNetwork/QAbstractSocket \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		connector.h \
		/opt/Qt5.8/include/QtNetwork/QTcpSocket \
		/opt/Qt5.8/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/QObject \
		const.h \
		encoder.h \
		/opt/Qt5.8/include/QtWidgets/QApplication \
		/opt/Qt5.8/include/QtWidgets/qapplication.h \
		/opt/Qt5.8/include/QtCore/qcoreapplication.h \
		/opt/Qt5.8/include/QtCore/qeventloop.h \
		/opt/Qt5.8/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.8/include/QtGui/qguiapplication.h \
		/opt/Qt5.8/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt5.8/include/QtWidgets/QMainWindow \
		/opt/Qt5.8/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.8/include/QtGui/qtguiglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtGui/qtgui-config.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.8/include/QtWidgets/qwidget.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qmargins.h \
		/opt/Qt5.8/include/QtGui/qpaintdevice.h \
		/opt/Qt5.8/include/QtCore/qrect.h \
		/opt/Qt5.8/include/QtCore/qsize.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtGui/qpalette.h \
		/opt/Qt5.8/include/QtGui/qcolor.h \
		/opt/Qt5.8/include/QtGui/qrgb.h \
		/opt/Qt5.8/include/QtGui/qrgba64.h \
		/opt/Qt5.8/include/QtGui/qbrush.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtGui/qmatrix.h \
		/opt/Qt5.8/include/QtGui/qpolygon.h \
		/opt/Qt5.8/include/QtGui/qregion.h \
		/opt/Qt5.8/include/QtCore/qdatastream.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qline.h \
		/opt/Qt5.8/include/QtGui/qtransform.h \
		/opt/Qt5.8/include/QtGui/qpainterpath.h \
		/opt/Qt5.8/include/QtGui/qimage.h \
		/opt/Qt5.8/include/QtGui/qpixelformat.h \
		/opt/Qt5.8/include/QtGui/qpixmap.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtGui/qfont.h \
		/opt/Qt5.8/include/QtGui/qfontmetrics.h \
		/opt/Qt5.8/include/QtGui/qfontinfo.h \
		/opt/Qt5.8/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.8/include/QtGui/qcursor.h \
		/opt/Qt5.8/include/QtGui/qkeysequence.h \
		/opt/Qt5.8/include/QtGui/qevent.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qurl.h \
		/opt/Qt5.8/include/QtCore/qurlquery.h \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h \
		/opt/Qt5.8/include/QtGui/qvector2d.h \
		/opt/Qt5.8/include/QtGui/qtouchdevice.h \
		/opt/Qt5.8/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.8/include/QtGui/qicon.h \
		errorwindow.h \
		/opt/Qt5.8/include/QtWidgets/QDialog \
		/opt/Qt5.8/include/QtWidgets/qdialog.h \
		/opt/Qt5.8/include/QtNetwork/QAbstractSocket \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		connector.h \
		/opt/Qt5.8/include/QtNetwork/QTcpSocket \
		/opt/Qt5.8/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/QObject \
		const.h \
		encoder.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

connector.o: connector.cpp connector.h \
		/opt/Qt5.8/include/QtNetwork/QTcpSocket \
		/opt/Qt5.8/include/QtNetwork/qtcpsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/QObject \
		const.h \
		encoder.h \
		/opt/Qt5.8/include/QtCore/QFile \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connector.o connector.cpp

errorwindow.o: errorwindow.cpp errorwindow.h \
		/opt/Qt5.8/include/QtWidgets/QDialog \
		/opt/Qt5.8/include/QtWidgets/qdialog.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.8/include/QtGui/qtguiglobal.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtGui/qtgui-config.h \
		/opt/Qt5.8/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.8/include/QtWidgets/qwidget.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.8/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.8/include/QtCore/qobject.h \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		/opt/Qt5.8/include/QtCore/qlist.h \
		/opt/Qt5.8/include/QtCore/qalgorithms.h \
		/opt/Qt5.8/include/QtCore/qiterator.h \
		/opt/Qt5.8/include/QtCore/qhashfunctions.h \
		/opt/Qt5.8/include/QtCore/qpair.h \
		/opt/Qt5.8/include/QtCore/qbytearraylist.h \
		/opt/Qt5.8/include/QtCore/qstringlist.h \
		/opt/Qt5.8/include/QtCore/qregexp.h \
		/opt/Qt5.8/include/QtCore/qstringmatcher.h \
		/opt/Qt5.8/include/QtCore/qcoreevent.h \
		/opt/Qt5.8/include/QtCore/qscopedpointer.h \
		/opt/Qt5.8/include/QtCore/qmetatype.h \
		/opt/Qt5.8/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.8/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.8/include/QtCore/qobject_impl.h \
		/opt/Qt5.8/include/QtCore/qmargins.h \
		/opt/Qt5.8/include/QtGui/qpaintdevice.h \
		/opt/Qt5.8/include/QtCore/qrect.h \
		/opt/Qt5.8/include/QtCore/qsize.h \
		/opt/Qt5.8/include/QtCore/qpoint.h \
		/opt/Qt5.8/include/QtGui/qpalette.h \
		/opt/Qt5.8/include/QtGui/qcolor.h \
		/opt/Qt5.8/include/QtGui/qrgb.h \
		/opt/Qt5.8/include/QtGui/qrgba64.h \
		/opt/Qt5.8/include/QtGui/qbrush.h \
		/opt/Qt5.8/include/QtCore/qvector.h \
		/opt/Qt5.8/include/QtGui/qmatrix.h \
		/opt/Qt5.8/include/QtGui/qpolygon.h \
		/opt/Qt5.8/include/QtGui/qregion.h \
		/opt/Qt5.8/include/QtCore/qdatastream.h \
		/opt/Qt5.8/include/QtCore/qiodevice.h \
		/opt/Qt5.8/include/QtCore/qline.h \
		/opt/Qt5.8/include/QtGui/qtransform.h \
		/opt/Qt5.8/include/QtGui/qpainterpath.h \
		/opt/Qt5.8/include/QtGui/qimage.h \
		/opt/Qt5.8/include/QtGui/qpixelformat.h \
		/opt/Qt5.8/include/QtGui/qpixmap.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer.h \
		/opt/Qt5.8/include/QtCore/qshareddata.h \
		/opt/Qt5.8/include/QtCore/qhash.h \
		/opt/Qt5.8/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.8/include/QtGui/qfont.h \
		/opt/Qt5.8/include/QtGui/qfontmetrics.h \
		/opt/Qt5.8/include/QtGui/qfontinfo.h \
		/opt/Qt5.8/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.8/include/QtGui/qcursor.h \
		/opt/Qt5.8/include/QtGui/qkeysequence.h \
		/opt/Qt5.8/include/QtGui/qevent.h \
		/opt/Qt5.8/include/QtCore/qvariant.h \
		/opt/Qt5.8/include/QtCore/qmap.h \
		/opt/Qt5.8/include/QtCore/qdebug.h \
		/opt/Qt5.8/include/QtCore/qtextstream.h \
		/opt/Qt5.8/include/QtCore/qlocale.h \
		/opt/Qt5.8/include/QtCore/qset.h \
		/opt/Qt5.8/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.8/include/QtCore/qurl.h \
		/opt/Qt5.8/include/QtCore/qurlquery.h \
		/opt/Qt5.8/include/QtCore/qfile.h \
		/opt/Qt5.8/include/QtCore/qfiledevice.h \
		/opt/Qt5.8/include/QtGui/qvector2d.h \
		/opt/Qt5.8/include/QtGui/qtouchdevice.h \
		/opt/Qt5.8/include/QtNetwork/QAbstractSocket \
		/opt/Qt5.8/include/QtNetwork/qabstractsocket.h \
		/opt/Qt5.8/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt5.8/include/QtNetwork/qtnetwork-config.h \
		const.h \
		ui_errorwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorwindow.o errorwindow.cpp

encoder.o: encoder.cpp encoder.h \
		/opt/Qt5.8/include/QtCore/QString \
		/opt/Qt5.8/include/QtCore/qstring.h \
		/opt/Qt5.8/include/QtCore/qchar.h \
		/opt/Qt5.8/include/QtCore/qglobal.h \
		/opt/Qt5.8/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.8/include/QtCore/qconfig.h \
		/opt/Qt5.8/include/QtCore/qtcore-config.h \
		/opt/Qt5.8/include/QtCore/qsystemdetection.h \
		/opt/Qt5.8/include/QtCore/qprocessordetection.h \
		/opt/Qt5.8/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.8/include/QtCore/qtypeinfo.h \
		/opt/Qt5.8/include/QtCore/qsysinfo.h \
		/opt/Qt5.8/include/QtCore/qlogging.h \
		/opt/Qt5.8/include/QtCore/qflags.h \
		/opt/Qt5.8/include/QtCore/qtypetraits.h \
		/opt/Qt5.8/include/QtCore/qatomic.h \
		/opt/Qt5.8/include/QtCore/qbasicatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.8/include/QtCore/qgenericatomic.h \
		/opt/Qt5.8/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.8/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.8/include/QtCore/qglobalstatic.h \
		/opt/Qt5.8/include/QtCore/qmutex.h \
		/opt/Qt5.8/include/QtCore/qnumeric.h \
		/opt/Qt5.8/include/QtCore/qversiontagging.h \
		/opt/Qt5.8/include/QtCore/qbytearray.h \
		/opt/Qt5.8/include/QtCore/qrefcount.h \
		/opt/Qt5.8/include/QtCore/qnamespace.h \
		/opt/Qt5.8/include/QtCore/qarraydata.h \
		/opt/Qt5.8/include/QtCore/qstringbuilder.h \
		const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encoder.o encoder.cpp

ver4_plugin_import.o: /home/Vyacheslav/Projects/Ver4/ver4_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ver4_plugin_import.o /home/Vyacheslav/Projects/Ver4/ver4_plugin_import.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_connector.o: moc_connector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connector.o moc_connector.cpp

moc_errorwindow.o: moc_errorwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errorwindow.o moc_errorwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

